# filebrowser/build.yaml
build_from:
  aarch64: "filebrowser/filebrowser:v2.32.0"
  amd64: "filebrowser/filebrowser:v2.32.0"
  armv7: "filebrowser/filebrowser:v2.32.0"
labels:
  io.hass.name: "FileBrowser"
  io.hass.description: "Web File Browser with material design, accessible via Ingress."
  io.hass.arch: "{arch}" # This will be replaced by the build system
  io.hass.type: "addon"
  io.hass.version: "0.1.6h" # Match config.yaml version
  org.opencontainers.image.title: "Home Assistant Add-on: FileBrowser"
  org.opencontainers.image.description: "Web File Browser integrated into Home Assistant with Ingress support."
  org.opencontainers.image.source: "https://github.com/el/ha-addons" # Update if your repo path is different
  org.opencontainers.image.licenses: "MIT"
  io.hass.url: "https://github.com/el/ha-addons/tree/main/filebrowser" # Update if your repo path is different
