# filebrowser/config.yaml
name: "FileBrowser"
version: "0.1.7" # Updated version
slug: "filebrowser"
description: "Web File Browser with material design, accessible via Ingress (using HA base image)."
url: "https://github.com/el/ha-addons/tree/main/filebrowser"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
  - "armhf"
init: false # run.sh will be PID 1, but with bashio environment
# image: "ghcr.io/el/ha-addons/filebrowser/{arch}"
ports:
  "80/tcp": 8080
ports_description:
  "80/tcp": "FileBrowser web interface (direct access)"
ingress: true
ingress_port: 80 # FileBrowser will listen on this port inside the container
ingress_entry: "/"
panel_icon: "mdi:folder-multiple"
map:
  - "share:rw"
  - "config:rw"
  - "ssl:ro"
  - "media:rw"
options:
  root_directory: "/share"
  database_file: "/config/filebrowser/filebrowser.db"
  log_level: "info"
  no_auth: false
  allow_commands: true # Note: FileBrowser's default compile might not include all commands
  allow_edit: true
  allow_new: true
  allow_publish: false
  # 'commands' option removed as it's not a direct FileBrowser flag
schema:
  root_directory: "str"
  database_file: "str"
  log_level: "list(debug|info|warn|error)?"
  no_auth: "bool?"
  allow_commands: "bool?"
  allow_edit: "bool?"
  allow_new: "bool?"
  allow_publish: "bool?"
startup: "application"
webui: "http://[HOST]:[PORT:80]"
