# filebrowser/config.yaml
name: "FileBrowser"
version: "0.1.4" # Incremented version for Ingress update
slug: "filebrowser"
description: "Web File Browser with material design, accessible via Ingress."
url: "https://github.com/el/ha-addons/tree/main/filebrowser"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
  - "armhf"
init: false
# image: "ghcr.io/el/ha-addons/filebrowser/{arch}"
ports:
  "80/tcp": 8080 # For optional direct access
ports_description:
  "80/tcp": "FileBrowser web interface (direct access - for advanced users or if Ingress fails)"
ingress: true
ingress_port: 80 # FileBrowser will listen on port 80 inside the container
ingress_stream: true
ingress_entry: "/" # FileBrowser serves from its root, --baseurl will handle the Ingress path
panel_icon: "mdi:folder-multiple"
map:
  - "share:rw"
  - "config:rw"
  - "ssl:ro"
  - "media:rw"
options:
  root_directory: "/share"
  database_file: "/config/filebrowser/filebrowser.db"
  # port: 80 # Removed - internal port is fixed to 80 for Ingress
  # base_url: "" # Removed - Ingress handles the base URL
  log_level: "info"
  no_auth: false
  allow_commands: true
  allow_edit: true
  allow_new: true
  allow_publish: false
  commands: "git,svn,hg"
schema:
  root_directory: "str"
  database_file: "str"
  log_level: "list(debug|info|warn|error)?"
  no_auth: "bool?"
  allow_commands: "bool?"
  allow_edit: "bool?"
  allow_new: "bool?"
  allow_publish: "bool?"
  commands: "str?"
startup: "application"
webui: "http://[HOST]:[PORT:80]" # This still refers to the direct access port mapped in Network settings
