name: "File Browser"
version: "2.32.0"
slug: "filebrowser"
description: "filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files"
url: "https://github.com/el/ha-addons/tree/main/filebrowser"
arch:
  - "aarch64"
  - "amd64"
init: false
ingress: true
ingress_port: 8071
ingress_stream: true
panel_admin: false
panel_icon: mdi:file-search
map:
  - addon_config:rw
  - media:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - addons:rw
  - backup:rw
  - share:rw
  - ssl:rw
environment:
  FM_HOME: /config
  HOME: /config
options:
  CUSTOM_RESULTS: false
  IPINFO_APIKEY: ""
schema:
  CUSTOM_RESULTS: "bool?"
  IPINFO_APIKEY: "str?"
# image: "ghcr.io/el/ha-addons/filebrowser/{arch}"
ports:
  "80/tcp": 8071
ports_description:
  "80/tcp": "File Browser web interface"
