name: "LibreSpeed"
version: "0.1.2"
slug: "librespeed"
description: "A self-hosted speedtest using the linuxserver/librespeed Docker image."
url: "https://github.com/el/ha-addons/tree/main/librespeed"
arch:
  - "aarch64"
  - "amd64"
init: false
ingress: true
panel_admin: false
panel_icon: mdi:speedometer
map:
  - "share:rw"
options: {}
schema: {}
# image: "ghcr.io/el/ha-addons/librespeed/{arch}"
ports:
  "80/tcp": 80
ports_description:
  "80/tcp": "LibreSpeed web interface"
