name: "LibreSpeed"
version: "0.1.5"
slug: "librespeed"
description: "A self-hosted speedtest using the linuxserver/librespeed Docker image."
url: "https://github.com/el/ha-addons/tree/main/librespeed"
arch:
  - "aarch64"
  - "amd64"
init: false
ingress: true
ingress_port: 80
ingress_stream: true
panel_admin: false
panel_icon: mdi:speedometer
map:
  - "share:rw"
options:
  CUSTOM_RESULTS: false
  IPINFO_APIKEY: ""
schema:
  CUSTOM_RESULTS: "bool?"
  IPINFO_APIKEY: "str?"
# image: "ghcr.io/el/ha-addons/librespeed/{arch}"
ports:
  "80/tcp": 80
ports_description:
  "80/tcp": "LibreSpeed web interface"
